version: '3.8'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - NEXT_PUBLIC_APP_URL=https://pediatric-exam-app.com
      - DATABASE_URL=postgresql://app_user:secure_password@db:5432/pediatric_exam_app
      - AUTH_SECRET=your-super-secret-auth-key-change-this-in-production
      - CORS_ORIGINS=https://pediatric-exam-app.com,https://www.pediatric-exam-app.com
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pediatric_exam_app
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  # 必要に応じてデータベースやその他のサービスを追加
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: pediatric_exam_app
  #     POSTGRES_USER: app_user
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  postgres_data:
